# Generated by Django 5.1 on 2025-11-13 16:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Autor')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('nacionalidad', models.CharField(default='Desconocida', max_length=50, verbose_name='Nacionalidad')),
                ('fecha_nacimiento', models.DateField(default='1900-01-01', verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Autor activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(default='Sin Apellido', max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('fecharegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('preferenciasgenero', models.TextField(blank=True, verbose_name='Preferencias de género')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('editorialid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Editorial')),
                ('nombreeditorial', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la editorial')),
                ('direccion', models.CharField(default='Sin dirección', max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(default='Sin teléfono', max_length=20, verbose_name='Teléfono')),
                ('emailcontacto', models.EmailField(default='sin@email.com', max_length=254, verbose_name='Email de contacto')),
                ('sitioweb', models.URLField(blank=True, verbose_name='Sitio web')),
                ('paisorigen', models.CharField(default='México', max_length=50, verbose_name='País de origen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Editorial',
                'verbose_name_plural': 'Editoriales',
                'ordering': ['nombreeditorial'],
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Libro')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del libro')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(choices=[('FIC', 'Ficción'), ('ROM', 'Romance'), ('TER', 'Terror'), ('CIE', 'Ciencia Ficción'), ('FAN', 'Fantasía'), ('HIS', 'Histórico'), ('BIO', 'Biografía'), ('INF', 'Infantil')], default='FIC', max_length=3, verbose_name='Género')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Precio')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad en stock')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='app_Libreria.autor', verbose_name='Autor')),
                ('editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='app_Libreria.editorial', verbose_name='Editorial')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Venta')),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de venta')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de la venta')),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('COM', 'Completada'), ('CAN', 'Cancelada'), ('DEV', 'Devuelta')], default='PEN', max_length=3, verbose_name='Estado de la venta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_Libreria.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_venta'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('detalleDeLaVentaid', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Detalle Venta')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precioUnitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio unitario')),
                ('iva', models.DecimalField(decimal_places=2, default=16.0, max_digits=5, verbose_name='IVA (%)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_venta', to='app_Libreria.libro', verbose_name='Libro')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_Libreria.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
    ]
